"""update length name lesson

Revision ID: 48302f7bdc0a
Revises: 91302a481080
Create Date: 2025-05-09 19:34:37.707017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48302f7bdc0a'
down_revision = '91302a481080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('youtube_url',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('youtube_url',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
