services:
  backend:
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - SQLALCHEMY_DATABASE_URI=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - ./coverage_html:/app/coverage_html
    command: sh -c "
      echo 'Waiting for postgres...' &&
      sleep 3 &&
      echo 'Running migrations...' &&
      flask db upgrade &&
      echo 'Running tests...' &&
      ./run_tests.sh &&
      echo 'Starting application...' &&
      flask run --host=0.0.0.0 --port=5000"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
